The following standards will be assessed on the ESB quiz:

## ALG-ESB

You should be able to:

- Describe terms like ensemble, voting, stacking, bagging, and boosting
- Give examples of algorithms for each ensemble type
- Discuss pros and cons of each ensemble type

## MOD-SEL

You should be able to:

- Identify appropriate algorithms for a given real-world scenarios
- Discuss tradeoffs of particular algorithms (interpretable, scalable, handling of missing data)
- Consider how decisions made in the modeling process may have ethical consequences

## Study Tips

Review the lecture slides, workbooks, homework assignments, and the associated lab.  
Quiz questions are similar (though not identical) to the types of questions covered in these materials.
You should be able to use appropriate terminology and apply the concepts covered in class to a variety of new scenarios.

The primary goal of each quiz is to give you an opportunity to apply concepts with clear and well-explained reasoning.  
Quizzes are also a valuable opportunity to receive feedback on your reasoning skills.  





