The following standards will be assessed on the NN quiz:

## ALG-NN

You should be able to:

- Describe terms like weights, bias, perceptron, neuron, feed-forward, backpropagation, activation function
- Draw a diagram of neural network architecture 
- Label the corresponding nodes ($X_i$, $Z_i^{(k)}$, $h_i^{(k)}$, $\hat{y}$, $b_i^{(k)})$ and edges $(w_{i,j}^{(k)})$ of the diagram
- Compute a given $Z_i^{(k)}$ and $h_i^{(k)}$ using an activation function $\sigma^{(k)}$


## ETH

You should be able to:

- Suggest improvements to a given scenario of data collection methods to help mitigate ethical concerns
- Communicate ideas clearly and justify reasoning

## Study Tips

Review the lecture slides, workbooks, homework assignments, and the associated lab.  
Quiz questions are similar (though not identical) to the types of questions covered in these materials.
You should be able to use appropriate terminology and apply the concepts covered in class to a variety of new scenarios.

The primary goal of each quiz is to give you an opportunity to apply concepts with clear and well-explained reasoning.  
Quizzes are also a valuable opportunity to receive feedback on your reasoning skills.  


### Formulas given

$\hat{y} = f(\beta + w_1x_1 + w_2x_2 + ... + w_nx_n)$ 

Unit step: $f(z) = \begin{cases} 1 & z \geq 0 \\ 0 & z < 0 \end{cases}$

Sigmoid: $f(z) = \frac{1}{1 + e^{-z}}$

ReLU: $f(z) = \max(0, z)$ <br><br>

$Z^{(1)}  =  W^{(1)} X + b^{(1)}$

$h^{(1)}  =  \sigma^{(1)}(Z^{(1)})$

$Z^{(k)}  =  W^{(k)}h^{(k-1)}  + b^{(k)}$

$h^{(k)}  =  \sigma^{(k)}(Z^{(k)})$

